[package]
name = "oi"
version = "0.1.0"
authors = ["Viktor Kuroljov <viktor@ku.family>"]
edition = "2018"

[dependencies]
notify-rust = "4"
lib-duration = { path = "../lib-duration" }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
reqwest = { version = "0.10", features = ["blocking", "json"] }
