Hours = {
  "hour" ~ ("s")?
  | "h" ~ ("r")?
}

Minutes = {
  "minute" ~ ("s")?
  | "m"
}

Seconds = {
  "second" ~ ("s")?
  | "sec" ~ ("s")?
  | "s"
}

Duration = {
  ASCII_DIGIT+
}

ShortDuration = _{
  Duration ~ (Hours | Minutes | Seconds)
}

LongDuration = _{
  Duration ~ " " ~ (Hours | Minutes | Seconds)
}

DurationExpr = {
  ShortDuration | LongDuration
}

Word = _{
  ASCII_ALPHA+
}

Expr = _{
  Word | DurationExpr
}

Input = _{
  SOI

  ~ Expr
  ~ (" " ~ Expr)*

  ~ EOI
}
