[package]
name = "oi"
version = "0.1.0"
authors = ["Viktor Kuroljov <viktor@ku.family>"]
edition = "2018"

[dependencies]
notify-rust = "4"
lib-duration = { path = "../lib-duration" }
rodio = "0.11"
chrono = "0.4"
directories = "3.0"
serde_yaml = "0.8"
