[package]
name = "lib-duration"
version = "0.1.0"
authors = ["Viktor Kuroljov <viktor@ku.family>"]
edition = "2018"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
chrono = "0.4"

[dev-dependencies]
pretty_assertions = "0.6"
