[package]
name = "lib-config"
version = "0.1.0"
authors = ["Viktor Kuroljov <viktor@ku.family>"]
edition = "2018"

[dependencies]
directories = "3.0"
serde_yaml = "0.8"
serde = "~1.0"
anyhow = "~1.0"
